include:
  - ../greptimedb-common.yml

services:
  django:
    build: django-app/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - ALLOWED_HOSTS=*
      - DJANGO_SETTINGS_MODULE=myproject.settings
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://greptimedb:4000/v1/otlp/v1/traces  # Optional

networks:
  demo-network:
