{
 "title": "Flight Map",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "icao24",
    "label": "icao24",
    "query": "SELECT DISTINCT icao24 FROM icao24_state where $__timeFilter(ts);"
   },
   {
    "name": "lat",
    "label": "Latitude",
    "query": "select latitude from icao24_state where $__timeFilter(ts) and icao24 = '$icao24' order by ts desc;"
   },
   {
    "name": "lon",
    "label": "longitude",
    "query": "select longitude from icao24_state where $__timeFilter(ts) and icao24 = '$icao24' order by ts desc;"
   },
   {
    "name": "h3_resolution",
    "label": "H3 Resolution",
    "query": "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15"
   }
  ]
 },
 "panels": [
  {
   "title": "Flight Map",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select icao24, longitude, latitude, baro_altitude, geo_altitude, velocity, geohash(latitude, longitude, 7) as geohash from icao24_state where icao24 = '$icao24' and $__timeFilter(ts) order by ts desc limit 500;"
    }
   ]
  },
  {
   "title": "Velocity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "select\n  ts,\n  velocity as value\nfrom\n  icao24_state\nwhere\n  icao24 = '$icao24'\n  and $__timeFilter(ts)\n  and h3(latitude, longitude, $h3_resolution) = h3($lat, $lon, $h3_resolution)\norder by ts desc;"
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "select\n  ts,\n  baro_altitude as value\nfrom\n  icao24_state\nwhere\n  icao24 = '$icao24'\n  and $__timeFilter(ts)\n  and h3(latitude, longitude, $h3_resolution) = h3($lat, $lon, $h3_resolution)\norder by\n  ts desc;"
    }
   ]
  }
 ]
}