[sources.file_source]
type = "file"
data_dir = "/logs"
include = [ "/logs/the-access.log" ]
# 512 mb
max_read_bytes = 536870912


[sinks.sink_greptime_logs]
type = "greptimedb_logs"
table = "demo_table"
pipeline_name = "demo_pipeline"
compression = "gzip"
inputs = [ "file_source" ]
endpoint = "http://greptimedb:4000"
