include:
  - ../greptimedb-common.yml
services:
  envsubst:
    image: docker.io/widerplan/envsubst
    command: "-i /config_input/config.alloy.tpl -o /config_output/config.alloy"
    volumes:
      - ./config.alloy.tpl:/config_input/config.alloy.tpl
      - config:/config_output
    env_file:
      - path: "greptime.env"
        required: false
    init: true

  grafana:
    image: docker.io/grafana/grafana:11.2.0
    ports:
      - 3000:3000
    networks:
      - demo-network
    volumes:
      - ./grafana_provisioning:/etc/grafana/provisioning

  alloy:
    image: docker.io/grafana/alloy:v1.4.1
    command: run --server.http.listen-addr=0.0.0.0:12345 /etc/alloy/config.alloy
    ports:
      - 12345:12345
    networks:
      - demo-network
    volumes:
      - config:/etc/alloy
      - ./foo.txt:/tmp/foo.txt
    depends_on:
      envsubst:
        condition: service_completed_successfully

networks:
  demo-network:

volumes:
  config:
