services:
  api:
    networks:
      dify-monitoring:
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        fluentd-async: "true"
        tag: dify.api

  worker:
    networks:
      dify-monitoring:
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        fluentd-async: "true"
        tag: dify.worker

  nginx:
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        fluentd-async: "true"
        tag: dify.nginx

networks:
  dify-monitoring:
    external: true
