include:
  - ../greptimedb-common.yml
services:
  ingester:
    build:
      context: ./ingester
      dockerfile: Dockerfile
    networks:
      - demo-network
    environment:
      - ICAO_AIRPORT_CODE=${ICAO_AIRPORT_CODE:-KSFO}
      - OPENSKY_USERNAME=${OPENSKY_USERNAME}
      - OPENSKY_PASSWORD=${OPENSKY_PASSWORD}
    depends_on:
      greptimedb:
        condition: service_started

  grafana:
    image: docker.io/grafana/grafana:11.2.0
    ports:
      - 3000:3000
    networks:
      - demo-network
    volumes:
      - ./grafana_provisioning:/etc/grafana/provisioning

networks:
  demo-network:
