services:
  greptimedb:
    image: docker.io/greptime/greptimedb:v0.9.2
    command: standalone start --http-addr=0.0.0.0:4000 --rpc-addr=0.0.0.0:4001 --mysql-addr=0.0.0.0:4002 --postgres-addr 0.0.0.0:4003
    ports:
      - 4000:4000
      - 4001:4001
      - 4002:4002
      - 4003:4003
    networks:
      - demo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:4000/health"]
      interval: 3s
      timeout: 3s
      retries: 5

  ingester:
    build:
      context: ./ingester
      dockerfile: Dockerfile
    networks:
      - demo-network
    environment:
      - ICAO_AIRPORT_CODE=${ICAO_AIRPORT_CODE:-KSFO}
      - OPENSKY_USERNAME=${OPENSKY_USERNAME}
      - OPENSKY_PASSWORD=${OPENSKY_PASSWORD}
    depends_on:
      greptimedb:
        condition: service_started

networks:
  demo-network:
