include:
  - ../greptimedb-common.yml

services:
  envsubst:
    image: docker.io/widerplan/envsubst
    command: "-i /config_input/vector.toml -o /config_output/vector.toml"
    volumes:
      - ./vector.toml:/config_input/vector.toml
      - config:/config_output
    env_file:
      - path: "greptime.env"
        required: false
    init: true

  postgresql:
    image: docker.io/postgres:17
    ports:
      - 5432:5432
    networks:
      - demo-network
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    env_file:
      - path: "greptime.env"
        required: false

  vector:
    image: docker.io/timberio/vector:0.43.X-alpine
    networks:
      - demo-network
    volumes:
      - config:/config_data
    command: "-c /config_data/vector.toml"
    depends_on:
      envsubst:
        condition: service_completed_successfully


networks:
  demo-network:

volumes:
  config:
