include:
  - ../greptimedb-common.yml

services:
  ollama:
    container_name: my-ollama
    image: ollama/ollama:0.17.7
    ports:
      - "127.0.0.1:11434:11434"
    networks:
      - demo-network

  otel-collector:
    image: docker.io/otel/opentelemetry-collector-contrib:0.120.0
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "127.0.0.1:13133:13133" # health_check extension
      - "127.0.0.1:4317:4317"   # OTLP gRPC receiver
      - "127.0.0.1:4318:4318"   # OTLP http receiver
    networks:
      - demo-network

  llm-joke-app:
    build: .
    depends_on:
      - ollama
      - otel-collector
    networks:
      - demo-network
    profiles:
      - run

networks:
  demo-network:
    driver: bridge
