{
 "title": "GreptimeDB Analysis",
 "tags": [
  "nginx access log",
  "continuous aggregation",
  "log pipeline"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "traceIdTerm", "label": "traceIdTerm", "query": "sleepify" }
  ]
 },
 "panels": [
  {
   "title": "Total requests - Summary",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) as count\nFROM ngx_access_log\nWHERE $__timeFilter(access_time);"
    }
   ]
  },
  {
   "title": "Requests Over Time (pre-aggregation with flow)",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_window,\n  sum(total_logs) as total_logs\nFROM ngx_statistics\nWHERE $__timeFilter(time_window)\nGROUP BY time_window\nORDER BY time_window"
    }
   ]
  },
  { "title": "Request Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Status Code (partial aggregation on top of flow)",
   "type": "piechart",
   "description": "Number of requests per streaming format",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  status::string as s,\n  sum(total_logs) as count\nFROM ngx_statistics\nWHERE $__timeFilter(time_window)\nGROUP BY s\nORDER BY count desc\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Referer",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 13, "w": 4, "x": 6, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  referer,\n  count(*) as count,\nFROM ngx_access_log\nWHERE $__timeFilter(access_time)\nGROUP BY referer\nORDER BY count desc\nLIMIT 100"
    }
   ]
  },
  {
   "title": "User Agent (extract platform in pipeline)",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 13, "w": 14, "x": 10, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  agent,\n  ua_platform,\n  count(*) as count,\nFROM ngx_access_log\nWHERE $__timeFilter(access_time)\nGROUP BY agent, ua_platform\nORDER BY count desc\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Payload size (flow aggregation) ",
   "type": "timeseries",
   "description": "Number of requests per streaming format",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "select \n  min_size,\n  max_size,\n  avg_size,\n  time_window\nfrom ngx_statistics\nwhere $__timeFilter(time_window) \n  AND status = 200;"
    }
   ]
  },
  {
   "title": "Number of large payload (flow conditional aggregation) ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "rawSql": "select \n  status::string as s,\n  sum(high_size_count) as count\nfrom ngx_statistics\nwhere $__timeFilter(time_window)\ngroup by s\norder by s;"
    }
   ]
  },
  { "title": "Server Side Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "QPS",
   "type": "timeseries",
   "description": "Number of requests per streaming format",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    { "expr": "rate(query_latency_count[30s])", "legendFormat": "QPS" }
   ]
  },
  {
   "title": "Query Latency",
   "type": "timeseries",
   "description": "Number of requests per streaming format",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, query_latency_bucket)",
     "legendFormat": "latency-p95"
    },
    {
     "expr": "histogram_quantile(0.99, query_latency_bucket)",
     "legendFormat": "latency-p99"
    }
   ]
  },
  {
   "title": "Latency top 10",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "rawSql": "select timestamp, delay, trace_id\nfrom server_log\nwhere $__timeFilter(timestamp)\norder by delay desc\nlimit 10"
    }
   ]
  },
  {
   "title": "GC object rate",
   "type": "timeseries",
   "description": "Number of requests per streaming format",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "rate(python_gc_objects_collected_total[30s])",
     "legendFormat": "generation-{{generation}}"
    }
   ]
  },
  { "title": "Raw Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Newest 50 raw logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "rawSql": "SELECT\n  concat(endpoint, ' ', method, ' ', trace_id), protocol, ua_platform, referer, client, access_time, status, size, agent\nFROM ngx_access_log\nWHERE\n  $__timeFilter(access_time)\nORDER BY access_time\nLIMIT 50"
    }
   ]
  },
  {
   "title": "Global view of top 10 latency by user namespace (full text search)",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "rawSql": "with top10 as (\n    select *\n    from server_log\n    where $__timeFilter(timestamp)\n      AND matches_term(trace_id, ${traceIdTerm:sqlstring})\n    order by delay desc\n    limit 10\n)\nselect access_time, top10.trace_id, client, ua_platform, referer, method, endpoint, protocol, status, size, agent, payload_size, delay\nfrom ngx_access_log\n    right join top10\n    on ngx_access_log.trace_id = top10.trace_id\norder by top10.delay desc;"
    }
   ]
  }
 ]
}