apiVersion: 1

datasources:
  - name: GreptimeDB
    type: mysql
    uid: greptimedb-mysql
    url: greptimedb:4002
    database: public
    isDefault: true
    editable: true

  - name: GreptimeDB-Prometheus
    type: prometheus
    uid: greptimedb-prometheus
    url: http://greptimedb:4000/v1/prometheus
    isDefault: false
    editable: true

  - name: GreptimeDB-Plugin
    type: info8fcc-greptimedb-datasource
    uid: greptimedb-plugin
    isDefault: false
    editable: true
    jsonData:
      host: http://greptimedb:4000
      defaultDatabase: public
      logs:
        defaultDatabase: public
        defaultTable: genai_conversations
        otelEnabled: true
        timeColumn: timestamp
        messageColumn: body
        levelColumn: severity_text
        traceIdColumn: trace_id
        selectContextColumns: true
        contextColumns:
          - trace_id
          - span_id
          - scope_name
      traces:
        defaultDatabase: public
        defaultTable: opentelemetry_traces
        otelEnabled: true
        traceIdColumn: trace_id
        spanIdColumn: span_id
        parentSpanIdColumn: parent_span_id
        serviceNameColumn: service_name
        operationNameColumn: span_name
        startTimeColumn: timestamp
        durationColumn: duration_nano
        durationUnit: nanoseconds
