services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    command:
      - '--path.rootfs=/'
    networks:
      - demo-network

  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    networks:
      - demo-network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    depends_on:
      - node_exporter
    ports:
      - 9090:9090

  grafana:
    image: docker.io/grafana/grafana:11.1.0
    ports:
      - 3000:3000
    networks:
      - demo-network
    restart: always


networks:
  demo-network:
