services:
  envsubst:
    image: docker.io/widerplan/envsubst
    command: "-i /config_input/prometheus.yml.tpl -o /config_output/prometheus.yml"
    volumes:
      - ./prometheus.yml.tpl:/config_input/prometheus.yml.tpl
      - config:/config_output
    env_file:
      - path: "greptime.env"
        required: false
    init: true

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    command:
      - '--path.rootfs=/'
    networks:
      - demo-network

  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    networks:
      - demo-network
    volumes:
      - config:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    depends_on:
      - node_exporter
      - envsubst
    ports:
      - 9090:9090

networks:
  demo-network:
volumes:
  config:
