processors:
  - dissect:
      fields:
        - message
      patterns:
        - '%{ip} - - [%{datetime}] "%{method} %{path} %{protocol}" %{status} %{size} "-" "%{user_agent}"'
  - date:
      fields:
        - datetime
      formats:
        - "%d/%b/%Y:%H:%M:%S %z"
  - date:
      fields:
        - timestamp
      formats:
        - "%Y-%m-%dT%H:%M:%S%.3fZ"

transform:
  - fields:
      - ip
      - method
      - path
      - protocol
      - user_agent
    type: string
  - fields:
      - status
      - size
    type: uint32
  - fields:
      - datetime
    type: timestamp
    index: timestamp
  - fields:
      - timestamp
    type: timestamp
